-- Add HALL_OF_JUSTICE to Role enum
ALTER TABLE memberships MODIFY COLUMN role ENUM('OWNER','ADMIN','STAFF','CLIENT','HALL_OF_JUSTICE') NOT NULL;
ALTER TABLE invites MODIFY COLUMN role ENUM('OWNER','ADMIN','STAFF','CLIENT','HALL_OF_JUSTICE') NOT NULL;
